name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  Build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub	
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: configure build environment
      run: rustup default nightly
      run: rustup target add armv7-unknown-linux-gnueabihf
      run: apt install gcc-arm-linux-gnueabihf -y
    - name: build release
      run: cargo build --target=armv7-unknown-linux-gnueabihf --release
    - name: Build the Docker image
      run: |
        docker buildx build --platform linux/arm/v7 -t rust-rocket-app:latest .
    - name: push to docker hub
      run: |
        docker tag rust-rocket-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/rust-rocket-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rust-rocket-app:latest